"""Test generation from the UI map (spec 29).

Turns the discovered map into code a test author can use immediately, so Claude
never has to explore the browser to find a control:

    generated/ui-map.ts        typed locator constants per UI state (Playwright TS)
    generated/navigation.ts    goTo(state) helpers built from the navigation graph
    generated/smoke.spec.ts    one Playwright test per state, asserting its controls
    generated/ui_map.py        the same locators for playwright-python
    generated/README.md        what was skipped and why

Only locators the tool actually validated are emitted. LOW-confidence ones are
emitted as commented-out lines with the recommended `data-testid`, so a human
sees the gap instead of inheriting a flaky test.
"""
from __future__ import annotations

import json
import re
import time
from pathlib import Path
from typing import Any

from .logging_setup import get
from .store.uimap import UNSTABLE_FLAG

log = get("codegen")

HEADER = "// GENERATED by PhenomeOne UI Discovery - do not edit by hand.\n// Source: {src}\n// Generated: {when}\n"
PY_HEADER = "# GENERATED by PhenomeOne UI Discovery - do not edit by hand.\n# Source: {src}\n# Generated: {when}\n"

_IDENT_BAD = re.compile(r"[^A-Za-z0-9]+")


def _ident(text: str, fallback: str = "item") -> str:
    parts = [p for p in _IDENT_BAD.split(text or "") if p]
    if not parts:
        return fallback
    head = parts[0].lower()
    ident = head + "".join(p[:1].upper() + p[1:] for p in parts[1:])
    if not re.match(r"^[A-Za-z_]", ident):
        ident = "_" + ident
    return ident[:60]


def _const(text: str, fallback: str = "STATE") -> str:
    parts = [p for p in _IDENT_BAD.split(text or "") if p]
    return ("_".join(p.upper() for p in parts) or fallback)[:60]


def _class_name(sid: str) -> str:
    """`research-group-germplasms` -> `ResearchGroupGermplasms`."""
    parts = [p for p in _IDENT_BAD.split(sid or "") if p]
    name = "".join(p[:1].upper() + p[1:] for p in parts) or "State"
    if not re.match(r"^[A-Za-z_]", name):
        name = "S" + name
    return name[:60]


def _usable(el: dict[str, Any]) -> bool:
    loc = el.get("locator") or {}
    return bool(loc.get("js")) and el.get("confidence") in ("HIGH", "MEDIUM")


def _js_expr(loc: dict[str, Any]) -> str:
    return f"page.{loc['js']}"


def generate(ui_map: dict[str, Any], out_dir: Path, nav_graph: dict[str, Any] | None = None,
             source: str = "output/ui-map.json") -> dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)
    when = time.strftime("%Y-%m-%d %H:%M:%S")
    states: dict[str, Any] = ui_map.get("states") or {}
    stats = {"states": 0, "locators": 0, "skippedLow": 0, "skippedUnstable": 0,
         "deferredHidden": 0, "files": []}
    skipped: list[str] = []

    # ---------------------------------------------------------------- TS map
    ts = [HEADER.format(src=source, when=when),
          "import type { Page, Locator } from '@playwright/test';\n"]
    py = [PY_HEADER.format(src=source, when=when),
          "from playwright.sync_api import Page, Locator\n"]

    registry: list[tuple[str, str, str]] = []          # (state id, ts name, py class)
    deferred: dict[str, list[str]] = {}                # state -> props needing an open surface
    for sid, st in sorted(states.items()):
        els = st.get("elements") or {}
        usable = {k: v for k, v in els.items() if _usable(v)}
        if not usable:
            continue
        stats["states"] += 1
        fn = _ident(sid, "state")
        route = st.get("route") or ""
        label = st.get("label") or sid

        ts.append(f"\n/** UI state `{sid}` - {label}\n *  route: {route} "
                  f"| seen {st.get('timesSeen', 0)}x */")
        ts.append(f"export const {fn} = (page: Page) => ({{")
        cls = _class_name(sid)
        registry.append((sid, fn, cls))
        py.append(f"\n\nclass {cls}:")
        py.append(f'    """UI state `{sid}` - {label} (route: {route})."""\n')
        py.append("    def __init__(self, page: Page) -> None:")
        py.append("        self.page = page\n")

        used: set[str] = set()
        for key, el in sorted(usable.items(), key=lambda kv: str(kv[1].get("logicalName"))):
            loc = el["locator"]
            name = _ident(el.get("logicalName") or key, "control")
            while name in used:
                name += "2"
            used.add(name)
            flags = el.get("flags") or []
            note = ""
            if UNSTABLE_FLAG in flags:
                note = "   // WARNING: this locator has changed between runs"
                stats["skippedUnstable"] += 1
            hidden = loc.get("validation") == "deferred-hidden" or el.get("visible") is False
            doc = f"{el.get('type')} - {el.get('confidence')}"
            if hidden:
                ctx = el.get("context") or {}
                where = ctx.get("dialog") or ctx.get("menu") or "its container"
                doc += f" - NOT VISIBLE in this state: open {where} first"
                stats["deferredHidden"] += 1
                deferred.setdefault(sid, []).append(_ident(name))
            ts.append(f"  /** {doc} */")
            ts.append(f"  {name}: (): Locator => {_js_expr(loc)},{note}")
            py.append("    @property")
            py.append(f"    def {_ident(name)}(self) -> Locator:")
            py.append(f'        """{doc}"""')
            py.append(f"        return self.page.{loc.get('python') or loc['js']}")
            stats["locators"] += 1

        for key, el in sorted(els.items()):
            if _usable(el):
                continue
            rec = el.get("recommendation") or "no reliable locator available"
            ts.append(f"  // SKIPPED {el.get('logicalName')!r} ({el.get('confidence')}): {rec}")
            stats["skippedLow"] += 1
            skipped.append(f"{sid} / {el.get('logicalName')}: {rec}")
        ts.append("});")

    # A registry so callers can go from a discovered state id straight to its
    # page object, without reconstructing the generated identifier.
    ts.append("\n/** Discovered state id -> its locator factory. */")
    ts.append("export const STATES = {")
    for sid, fn, _cls in registry:
        ts.append(f"  {json.dumps(sid)}: {fn},")
    ts.append("} as const;")

    # Machine-readable list of the locators that need a dialog/menu opened
    # first, so a consumer can filter them out of a "is everything present?"
    # sweep instead of treating them as broken.
    py.append("\n\n# state id -> properties that only resolve once their dialog/menu is open.")
    py.append("NEEDS_OPENING = {")
    for sid, props in sorted(deferred.items()):
        py.append(f"    {json.dumps(sid)}: {json.dumps(sorted(set(props)))},")
    py.append("}")

    ts.append("\n/** state id -> locators that need their dialog/menu opened first. */")
    ts.append("export const NEEDS_OPENING: Record<string, string[]> = {")
    for sid, props in sorted(deferred.items()):
        ts.append(f"  {json.dumps(sid)}: {json.dumps(sorted(set(props)))},")
    ts.append("};")

    py.append("\n\n# Discovered state id -> its page object.")
    py.append("STATES = {")
    for sid, _fn, cls in registry:
        py.append(f"    {json.dumps(sid)}: {cls},")
    py.append("}")

    # ------------------------------------------------------------ navigation
    nav = [HEADER.format(src=source, when=when),
           "import type { Page } from '@playwright/test';\n",
           "/** Navigation paths learned from the application itself. */",
           "export type StateId = " + (" | ".join(f"'{s}'" for s in sorted(states)) or "never") + ";\n",
           "export const NAV_STEPS: Record<string, { from: string; action: string; "
           "locator: string }[]> = {"]
    paths_by_state = _paths_from_root(ui_map, nav_graph)
    for sid, steps in sorted(paths_by_state.items()):
        nav.append(f"  '{sid}': [")
        for step in steps:
            nav.append(f"    {{ from: '{step['from']}', action: {json.dumps(step['action'])}, "
                       f"locator: {json.dumps(step['locator'] or '')} }},")
        nav.append("  ],")
    nav.append("};\n")
    nav.append("""/**
 * Walk from the application root to `state` by replaying the learned path.
 * Steps whose locator is unknown are skipped and reported by the caller.
 */
export async function goToState(page: Page, state: StateId): Promise<string[]> {
  const missing: string[] = [];
  for (const step of NAV_STEPS[state] ?? []) {
    if (!step.locator) { missing.push(step.action); continue; }
    // eslint-disable-next-line no-eval
    const locator = eval(`page.${step.locator}`);
    await locator.first().click();
  }
  return missing;
}
""")

    # ----------------------------------------------------------- smoke tests
    spec = [HEADER.format(src=source, when=when),
            "import { test, expect } from '@playwright/test';",
            "import { goToState } from './navigation';",
            "\n// One smoke test per discovered UI state. Each asserts the controls the",
            "// discovery tool validated are present, so a UI regression fails here first.",
            "\ntest.describe('PhenomeOne UI map smoke', () => {"]
    for sid, st in sorted(states.items()):
        els = [e for e in (st.get("elements") or {}).values()
               if _usable(e) and e.get("visible") and e.get("confidence") == "HIGH"]
        if not els:
            continue
        spec.append(f"\n  test('{sid} exposes its controls', async ({{ page }}) => {{")
        spec.append(f"    await goToState(page, '{sid}');")
        for el in els[:12]:
            spec.append(f"    await expect(page.{el['locator']['js']}).toBeVisible();")
        spec.append("  });")
    spec.append("});\n")

    readme = [f"# Generated Playwright assets\n",
              f"Source: `{source}`  \nGenerated: {when}\n",
              f"- `ui-map.ts` - {stats['locators']} validated locators across "
              f"{stats['states']} UI states\n",
              "- `navigation.ts` - learned navigation paths + `goToState()`\n",
              "- `smoke.spec.ts` - one test per state asserting its HIGH-confidence controls\n",
              "- `ui_map.py` - the same locators for playwright-python\n",
              f"\n## Skipped ({stats['skippedLow']})\n",
              "\nThese elements had no locator good enough to generate. Add the suggested\n"
              "`data-testid` in the application and re-run discovery.\n\n"]
    readme += [f"- {line}\n" for line in skipped[:200]]

    files = {
        "ui-map.ts": "\n".join(ts) + "\n",
        "navigation.ts": "\n".join(nav),
        "smoke.spec.ts": "\n".join(spec),
        "ui_map.py": "\n".join(py) + "\n",
        "README.md": "".join(readme),
    }
    for name, text in files.items():
        (out_dir / name).write_text(text, encoding="utf-8")
        stats["files"].append(name)
    log.info("Generated %d test asset(s) in %s: %d locators, %d states, %d skipped",
             len(files), out_dir, stats["locators"], stats["states"], stats["skippedLow"])
    return stats


def _paths_from_root(ui_map: dict[str, Any],
                     nav_graph: dict[str, Any] | None) -> dict[str, list[dict[str, Any]]]:
    """Shortest action path from a root state to every reachable state (BFS)."""
    edges = list((ui_map.get("navigation") or {}).values())
    if not edges and nav_graph:
        edges = nav_graph.get("edges") or []
    adj: dict[str, list[dict[str, Any]]] = {}
    incoming: set[str] = set()
    for e in edges:
        adj.setdefault(e["from"], []).append(e)
        incoming.add(e["to"])
    states = set((ui_map.get("states") or {}).keys())
    roots = sorted(states - incoming) or sorted(states)[:1]

    paths: dict[str, list[dict[str, Any]]] = {r: [] for r in roots}
    queue = list(roots)
    while queue:
        cur = queue.pop(0)
        for e in sorted(adj.get(cur, []), key=lambda x: str((x["action"] or {}).get("name"))):
            dest = e["to"]
            if dest in paths:
                continue
            act = e["action"] or {}
            paths[dest] = paths[cur] + [{"from": cur, "action": act.get("name") or act.get("type")
                                         or "?", "locator": act.get("locator")}]
            queue.append(dest)
    for sid in states:
        paths.setdefault(sid, [])
    return paths
