max_procs 3
max_time 3600
is_persistent 1
idle_time 300
work_dir /tmp/job_server
storage_handler NFS
queue_handler DB
revision 20873
changelog 907
email_sender support@phenome-networks.com

<Schema::PHN2>
    <connect_info>
        dsn               dbi:mysql:database=pheno20;host=10.200.32.21;port=3306
        user              phenome
        password          YzG!DaWBm$F9J9XhnY
        quote_names       1
        mysql_enable_utf8 1
    </connect_info>
    odbc_id pheno20
</Schema::PHN2>

<NFS>
</NFS>

<Storage uploads>
    path /data/public/
    ws_root https://phenome.gdmseeds.com/public
    work_dir /tmp/job_server/uploads
</Storage>

<Storage analyses>
    path /data/public/
    ws_root https://phenome.gdmseeds.com/public
    work_dir /tmp/job_server/analyses
</Storage>

<Storage images>
    path /data/public/
    ws_root https://phenome.gdmseeds.com/public
    work_dir /tmp/job_server/images
</Storage>

<Storage reports>
    path /data/public/
    ws_root https://phenome.gdmseeds.com/public
    work_dir /tmp/job_server/reports
</Storage>

<DB>
</DB>

<Queue>
    queue_name gdm-on-prem
</Queue>


