"""Self-contained HTML discovery report (spec 21).

No external assets, no network calls, and no secrets: session material, cookies
and credentials never reach this file. Everything shown is structural UI
metadata plus the locators generated for it.
"""
from __future__ import annotations

import html
import time
from typing import Any

from .. import paths
from ..logging_setup import get
from ..locator.generator import HIGH, LOW, MEDIUM
from ..navigation import graph as navgraph
from ..store.uimap import UNSTABLE_FLAG

log = get("reporting")

_CSS = """
:root{--bg:#12161c;--panel:#1a1f27;--line:#2a323d;--fg:#e6eaf0;--dim:#96a0ae;
--high:#3fb950;--med:#d29922;--low:#f85149;--accent:#58a6ff;--mono:ui-monospace,Consolas,monospace}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.55 -apple-system,Segoe UI,Roboto,sans-serif}
.wrap{max-width:1180px;margin:0 auto;padding:32px 20px 64px}
h1{font-size:24px;margin:0 0 4px}h2{font-size:16px;margin:36px 0 12px;letter-spacing:.04em;
text-transform:uppercase;color:var(--dim);border-bottom:1px solid var(--line);padding-bottom:6px}
h3{font-size:14px;margin:20px 0 8px}
.sub{color:var(--dim);margin:0 0 24px}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}
.card{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:14px 16px}
.card .n{font-size:26px;font-weight:600;font-variant-numeric:tabular-nums}
.card .l{color:var(--dim);font-size:12px;text-transform:uppercase;letter-spacing:.05em}
.card.high .n{color:var(--high)}.card.med .n{color:var(--med)}.card.low .n{color:var(--low)}
table{width:100%;border-collapse:collapse;font-size:13px}
th,td{text-align:left;padding:7px 10px;border-bottom:1px solid var(--line);vertical-align:top}
th{color:var(--dim);font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:.05em}
tbody tr:hover{background:#1e242d}
code,pre{font-family:var(--mono);font-size:12px}
code{background:#0e1217;border:1px solid var(--line);border-radius:4px;padding:1px 5px;color:#a5d6ff}
pre{background:#0e1217;border:1px solid var(--line);border-radius:8px;padding:14px;overflow-x:auto}
.tag{display:inline-block;padding:1px 7px;border-radius:99px;font-size:11px;font-weight:600}
.HIGH{background:rgba(63,185,80,.16);color:var(--high)}
.MEDIUM{background:rgba(210,153,34,.16);color:var(--med)}
.LOW{background:rgba(248,81,73,.16);color:var(--low)}
.flag{background:rgba(248,81,73,.16);color:var(--low);font-size:10px;margin-left:6px;
padding:1px 6px;border-radius:99px}
details{background:var(--panel);border:1px solid var(--line);border-radius:8px;margin:8px 0}
summary{cursor:pointer;padding:10px 14px;font-weight:600}
summary::marker{color:var(--dim)}
details .body{padding:0 14px 12px;overflow-x:auto}
.meta{color:var(--dim);font-weight:400;font-size:12px}
.bar{display:flex;height:8px;border-radius:99px;overflow:hidden;background:#0e1217;margin:10px 0 0}
.bar i{display:block}.bar .h{background:var(--high)}.bar .m{background:var(--med)}.bar .l{background:var(--low)}
.note{color:var(--dim);font-size:12px;margin-top:6px}
"""


def _esc(v: Any) -> str:
    return html.escape("" if v is None else str(v), quote=True)


def _card(n: Any, label: str, cls: str = "") -> str:
    return f'<div class="card {cls}"><div class="n">{_esc(n)}</div><div class="l">{_esc(label)}</div></div>'


def render(store: Any, environments: list[dict[str, Any]] | None = None,
           training_summary: dict[str, Any] | None = None) -> str:
    c = store.counts()
    conf = c["confidence"]
    total_conf = max(1, sum(conf.values()))
    nav = navgraph.build(store)
    envs = environments or store.data["application"].get("environments", [])
    env_list = ", ".join(_esc(e.get("origin")) for e in envs) or "(none recorded)"

    p = []
    p.append(f"<!-- generated by {paths.APP_NAME} -->")
    p.append(f"<title>PhenomeOne UI Discovery Report</title><style>{_CSS}</style>")
    p.append('<div class="wrap">')
    p.append("<h1>PhenomeOne UI Discovery</h1>")
    p.append(f'<p class="sub">Environment: {env_list}<br>Generated: '
             f'{time.strftime("%Y-%m-%d %H:%M:%S")}<br>Map created: '
             f'{_esc(store.data.get("createdAt"))} &middot; last updated: {_esc(store.data.get("updatedAt"))}</p>')

    # ---- totals
    p.append('<div class="cards">')
    p.append(_card(c["states"], "UI states"))
    p.append(_card(c["elements"], "Interactive elements"))
    p.append(_card(c["navigationPaths"], "Navigation paths"))
    p.append(_card(conf.get(HIGH, 0), "HIGH locators", "high"))
    p.append(_card(conf.get(MEDIUM, 0), "MEDIUM", "med"))
    p.append(_card(conf.get(LOW, 0), "LOW", "low"))
    p.append("</div>")
    p.append(f'<div class="bar"><i class="h" style="width:{conf.get(HIGH,0)/total_conf*100:.1f}%"></i>'
             f'<i class="m" style="width:{conf.get(MEDIUM,0)/total_conf*100:.1f}%"></i>'
             f'<i class="l" style="width:{conf.get(LOW,0)/total_conf*100:.1f}%"></i></div>')
    p.append('<p class="note">Locator quality: HIGH = validated unique test id / role+name / label. '
             'MEDIUM = validated unique but attribute- or text-based. LOW = ambiguous, positional, '
             'or unvalidated.</p>')

    # ---- training summary
    if training_summary:
        ts = training_summary
        p.append("<h2>Last training session</h2><div class=cards>")
        p.append(_card(f'{ts.get("durationSeconds", 0):.0f}s', "Duration"))
        p.append(_card(ts.get("statesSeen", 0), "States visited"))
        p.append(_card(len(ts.get("newStates") or []), "New states"))
        p.append(_card(ts.get("newNavigationPaths", 0), "New paths"))
        p.append(_card(ts.get("actionsObserved", 0), "User actions seen"))
        p.append(_card(f'{ts.get("avgScanMs", 0)} ms', "Avg scan"))
        p.append("</div>")

    # ---- element types
    p.append("<h2>Element types</h2><table><thead><tr><th>Type</th><th>Count</th></tr></thead><tbody>")
    for t, n in c["types"].items():
        p.append(f"<tr><td>{_esc(t)}</td><td>{n}</td></tr>")
    p.append("</tbody></table>")

    # ---- navigation
    p.append("<h2>Navigation graph</h2>")
    if nav["tree"]:
        p.append("<pre>" + _esc("\n".join(nav["tree"])) + "</pre>")
    else:
        p.append('<p class="note">No navigation paths learned yet - run Training Mode and '
                 'navigate through the application.</p>')
    if nav["edges"]:
        p.append("<table><thead><tr><th>From</th><th>Action</th><th>Locator</th><th>To</th>"
                 "<th>Seen</th></tr></thead><tbody>")
        for e in sorted(nav["edges"], key=lambda x: (x["from"], str(x["action"].get("name")))):
            a = e["action"]
            p.append(f"<tr><td>{_esc(e['from'])}</td>"
                     f"<td>{_esc(a.get('type'))}: <b>{_esc(a.get('name') or '?')}</b></td>"
                     f"<td>{'<code>'+_esc(a.get('locator'))+'</code>' if a.get('locator') else '<span class=meta>-</span>'}</td>"
                     f"<td>{_esc(e['to'])}</td><td>{e.get('timesSeen',1)}</td></tr>")
        p.append("</tbody></table>")

    # ---- weak locators
    weak = sorted(c["weak"], key=lambda w: (w.get("state", ""), w.get("logicalName", "")))
    p.append(f"<h2>Weak locators ({len(weak)})</h2>")
    if weak:
        p.append("<table><thead><tr><th>State</th><th>Element</th><th>Type</th><th>Locator</th>"
                 "<th>Matches</th><th>Quality</th></tr></thead><tbody>")
        for w in weak[:400]:
            loc = w.get("locator") or {}
            flag = f'<span class="flag">{UNSTABLE_FLAG}</span>' if UNSTABLE_FLAG in (w.get("flags") or []) else ""
            p.append(f"<tr><td>{_esc(w.get('state'))}</td>"
                     f"<td>{_esc(w.get('logicalName'))}{flag}</td>"
                     f"<td>{_esc(w.get('type'))}</td>"
                     f"<td><code>{_esc(loc.get('js'))}</code></td>"
                     f"<td>{_esc(loc.get('matches', '-'))}</td>"
                     f"<td><span class='tag {_esc(w.get('confidence'))}'>{_esc(w.get('confidence'))}</span></td></tr>")
        p.append("</tbody></table>")
        if len(weak) > 400:
            p.append(f'<p class="note">{len(weak)-400} further weak locators omitted from this table; '
                     f'all of them are in output/ui-map.json.</p>')
    else:
        p.append('<p class="note">None - every element resolved to a unique, high-quality locator.</p>')

    # ---- recommended test ids
    recs = [(w.get("state"), w.get("logicalName"), w.get("recommendation"))
            for w in weak if w.get("recommendation")]
    p.append(f"<h2>Recommended test IDs ({len(recs)})</h2>")
    if recs:
        p.append("<table><thead><tr><th>State</th><th>Element</th><th>Recommendation</th></tr></thead><tbody>")
        for state, name, rec in recs[:200]:
            p.append(f"<tr><td>{_esc(state)}</td><td>{_esc(name)}</td><td>{_esc(rec)}</td></tr>")
        p.append("</tbody></table>")
    else:
        p.append('<p class="note">No test-id additions needed.</p>')

    # ---- per state detail
    p.append("<h2>UI states</h2>")
    for sid, st in sorted(store.data["states"].items()):
        els = st.get("elements", {})
        sig = st.get("signals") or {}
        p.append(f"<details><summary>{_esc(sid)} <span class=meta>&middot; {len(els)} elements "
                 f"&middot; route {_esc(st.get('route'))} &middot; seen {st.get('timesSeen',0)}x</span></summary>"
                 f'<div class="body">')
        p.append(f'<p class="note">Label: {_esc(st.get("label"))} &middot; fingerprint '
                 f'<code>{_esc(st.get("fingerprint"))}</code>'
                 + (f' &middot; active tab <b>{_esc(sig.get("activeTab"))}</b>' if sig.get("activeTab") else "")
                 + (f' &middot; dialogs: {_esc(", ".join(sig.get("dialogs") or []))}' if sig.get("dialogs") else "")
                 + "</p>")
        p.append("<table><thead><tr><th>Element</th><th>Type</th><th>Recommended locator</th>"
                 "<th>Matches</th><th>Quality</th><th>Seen</th></tr></thead><tbody>")
        for el in sorted(els.values(), key=lambda e: (str(e.get("type")), str(e.get("logicalName")))):
            loc = el.get("locator") or {}
            flag = f'<span class="flag">{UNSTABLE_FLAG}</span>' if UNSTABLE_FLAG in (el.get("flags") or []) else ""
            extra = []
            if el.get("grid"):
                cols = ", ".join(el["grid"].get("columns") or [])
                extra.append(f'<div class="note">columns: {_esc(cols)} ({el["grid"].get("rowCount",0)} rows)</div>')
            if el.get("options"):
                extra.append(f'<div class="note">options: {_esc(", ".join(el["options"]))}</div>')
            p.append(f"<tr><td>{_esc(el.get('logicalName'))}{flag}{''.join(extra)}</td>"
                     f"<td>{_esc(el.get('type'))}</td>"
                     f"<td><code>{_esc(loc.get('js'))}</code></td>"
                     f"<td>{_esc(loc.get('matches', '-'))}</td>"
                     f"<td><span class='tag {_esc(el.get('confidence'))}'>{_esc(el.get('confidence'))}</span></td>"
                     f"<td>{el.get('timesSeen',0)}</td></tr>")
        p.append("</tbody></table></div></details>")

    p.append('<p class="note" style="margin-top:40px">Machine-readable output: '
             'output/ui-map.json, output/navigation-graph.json, output/application.json, '
             'output/training-summary.json. No credentials or session data are included in any '
             'of these files.</p>')
    p.append("</div>")
    return "\n".join(p)


def write(store: Any, path=None, environments=None, training_summary=None):
    path = path or paths.REPORT_FILE
    path.parent.mkdir(parents=True, exist_ok=True)
    html_text = "<!doctype html><meta charset='utf-8'>" + render(store, environments, training_summary)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(html_text, encoding="utf-8")
    tmp.replace(path)
    log.info("Report written -> %s", paths.rel(path))
    return path
